# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [4]:
a = [[4,10,11],[21,22,23],[31,32,33]]
b = np.ones((3,3))

print(a+b) 

[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]


### 2. Write a Python Program to Multiply Two Matrices?

In [5]:
print(a*b) 

[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]


### 3. Write a Python Program to Transpose a Matrix?

In [13]:
b = np.array(a)
b

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [11]:
b.transpose()

array([[ 4, 21, 31],
       [10, 22, 32],
       [11, 23, 33]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [14]:
my_str = input("Enter a string: ")

words = [word.lower() for word in my_str.split()]

words.sort()

print("The sorted words are:")
print(words)

Enter a string:  z d a b c f e


The sorted words are:
['a', 'b', 'c', 'd', 'e', 'f', 'z']


In [17]:
my_str = input("Enter a string: ")

words = [word for word in my_str]

words.sort()

print("The sorted words are:")
print(words)

Enter a string:  ZhYpPdAaCbB


The sorted words are:
['A', 'B', 'C', 'P', 'Y', 'Z', 'a', 'b', 'd', 'h', 'p']


### 5. Write a Python Program to Remove Punctuation From a String?

In [19]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, HAI, how are you??"

no_punct = ""

for i in my_str:
   if i not in punctuations:
       no_punct = no_punct + i

print(no_punct)

Hello HAI how are you
